### ISSUE TITLE
I'm Being Pedantic - The noise background doesn't look random enough

### ISSUE THREAD

**Issue by CurtisFenner** [jason-merlo/Adambots-Scouter#1]
Can you shuffle it around or something? It appears too structured and is distracting to me.
Not sure. Maybe I'm crazy, or maybe it just needs to be slightly muted.

**Comment by jason-merlo** [comment]
Yeah, I can change it a bit, didn’t notice it before, I was trying to
forget it was an image, but theres no other way to do it and it looks a bit
soft
- Jason
